In [ ]:
import math
import numpy
import random
import sklearn
import string
from collections import defaultdict
import numpy as np
import pandas as pd

In [ ]:
clothing_data = []
f = open("modcloth_final_data.json")
for l in f:
    d = eval(l)
    clothing_data.append(d)
f.close()

In [ ]:
reviews = []
f1 = open("renttherunway_final_data.json")
for l1 in f1:
    try:
      d = eval(l1)
    except:
      l1 = l1.replace('null', "'None'")
      d = eval(l1)
    reviews.append(d)
f1.close()

In [ ]:
modcloth = pd.DataFrame(clothing_data)[['item_id', 'size', 'height', 'fit', 'user_id']]
modcloth

item_id  size   height    fit user_id
0      123373     7  5ft 6in  small  991571
1      123373    13  5ft 2in  small  587883
2      123373     7  5ft 7in  small  395665
3      123373    21      NaN    fit  875643
4      123373    18  5ft 2in  small  944840
...       ...   ...      ...    ...     ...
82785  807722     8  5ft 8in    fit  727820
82786  807722    12  5ft 5in  small  197040
82787  807722    12  5ft 4in    fit  102493
82788  807722    12  5ft 3in    fit  756491
82789  807722     4      6ft    fit   78305

[82790 rows x 5 columns]

In [ ]:
d = modcloth['height'].str.replace('ft', '').str.replace('in','').str.split()
print(d)

0        [5, 6]
1        [5, 2]
2        [5, 7]
3           NaN
4        [5, 2]
          ...  
82785    [5, 8]
82786    [5, 5]
82787    [5, 4]
82788    [5, 3]
82789       [6]
Name: height, Length: 82790, dtype: object


In [ ]:
ft= d.str[0].astype('Int64').multiply(other=12)
inc = d.str[1].astype('Int64')
modcloth['height'] = ft.add(inc, fill_value= 0, axis =0)
modcloth

item_id  size  height    fit user_id
0      123373     7      66  small  991571
1      123373    13      62  small  587883
2      123373     7      67  small  395665
3      123373    21    <NA>    fit  875643
4      123373    18      62  small  944840
...       ...   ...     ...    ...     ...
82785  807722     8      68    fit  727820
82786  807722    12      65  small  197040
82787  807722    12      64    fit  102493
82788  807722    12      63    fit  756491
82789  807722     4      72    fit   78305

[82790 rows x 5 columns]

In [ ]:
runway = pd.DataFrame(reviews)[['fit', 'user_id', 'item_id', 'weight', 'height', 'size']]
runway

fit user_id  item_id  weight height  size
0       fit  420272  2260466  137lbs  5' 8"    14
1       fit  273551   153475  132lbs  5' 6"    12
2       fit  360448  1063761     NaN  5' 4"     4
3       fit  909926   126335  135lbs  5' 5"     8
4       fit  151944   616682  145lbs  5' 9"    12
...     ...     ...      ...     ...    ...   ...
192539  fit   66386  2252812  140lbs  5' 9"     8
192540  fit  118398   682043  100lbs  5' 1"     4
192541  fit   47002   683251  135lbs  5' 8"     8
192542  fit  961120   126335  165lbs  5' 6"    16
192543  fit  123612   127865  155lbs  5' 6"    16

[192544 rows x 6 columns]

In [ ]:
rheight = runway['height'].str.replace("'", '').str.replace('"','').str.split()
#print(rheight)
rft= rheight.str[0].astype('Int64').multiply(other=12)
rinc = rheight.str[1].astype('Int64')
runway['height'] = rft.add(rinc, fill_value= 0, axis =0)

In [ ]:
runway['weight'] = runway['weight'].str.replace('lbs','')
runway

fit user_id  item_id weight  height  size
0       fit  420272  2260466    137      68    14
1       fit  273551   153475    132      66    12
2       fit  360448  1063761    NaN      64     4
3       fit  909926   126335    135      65     8
4       fit  151944   616682    145      69    12
...     ...     ...      ...    ...     ...   ...
192539  fit   66386  2252812    140      69     8
192540  fit  118398   682043    100      61     4
192541  fit   47002   683251    135      68     8
192542  fit  961120   126335    165      66    16
192543  fit  123612   127865    155      66    16

[192544 rows x 6 columns]

In [ ]:
# item_id and user_id, fit
merged = pd.concat([modcloth, runway], ignore_index=True)
merged

item_id  size  height    fit user_id weight
0        123373     7      66  small  991571    NaN
1        123373    13      62  small  587883    NaN
2        123373     7      67  small  395665    NaN
3        123373    21    <NA>    fit  875643    NaN
4        123373    18      62  small  944840    NaN
...         ...   ...     ...    ...     ...    ...
275329  2252812     8      69    fit   66386    140
275330   682043     4      61    fit  118398    100
275331   683251     8      68    fit   47002    135
275332   126335    16      66    fit  961120    165
275333   127865    16      66    fit  123612    155

[275334 rows x 6 columns]

In [ ]:
# learn more about the datasets
runway_unique= runway.shape[0]
print('runway: ' + str((runway_unique)))

modcloth_unique = modcloth.shape[0]
print('modcloth: ' + str((modcloth_unique)))

print('users')

runway_unique_user = runway['user_id'].unique()
print('runway: ' + str(len(runway_unique_user)))

modcloth_unique_user = modcloth['user_id'].unique()
print('modcloth: ' + str(len(modcloth_unique_user)))

print('items')

runway_unique_item = runway.groupby(['item_id', 'size']).size()
print('runway: ' + str(len(runway_unique_item)))

modcloth_unique_item = modcloth.groupby(['item_id', 'size']).size()
print('modcloth: ' + str(len(modcloth_unique_item)))

print('fit')

runway_unique_fit = (runway['fit'] == 'fit').sum() / runway_unique
print('runway: ' + str(runway_unique_fit))

modcloth_unique_fit = (modcloth['fit'] == 'fit').sum() / modcloth_unique
print('modcloth: ' + str(modcloth_unique_fit))

print('small')

runway_unique_small = (runway['fit'] == 'small').sum() / runway_unique
print('runway: ' + str(runway_unique_small))

modcloth_unique_small = (modcloth['fit'] == 'small').sum() / modcloth_unique
print('modcloth: ' + str(modcloth_unique_small))

print('large')

runway_unique_large = (runway['fit'] == 'large').sum() / runway_unique
print('runway: ' + str(runway_unique_large))

modcloth_unique_large = (modcloth['fit'] == 'large').sum() / modcloth_unique
print('modcloth: ' + str(modcloth_unique_large))

print('1 user')

runway_one_user = runway[~runway.duplicated('user_id', keep=False)].shape[0] / runway_unique
print('runway: ' + str(runway_one_user))

modcloth_one_user = modcloth[~modcloth.duplicated('user_id', keep=False)].shape[0] / modcloth_unique
print('modcloth: ' + str(modcloth_one_user))

print('1 item')

runway_one_item = runway.groupby(['item_id', 'size']).filter(lambda x: len(x) == 1).shape[0] / len(runway_unique_item)
print('runway: ' + str(runway_one_item))

modcloth_one_item = modcloth.groupby(['item_id', 'size']).filter(lambda x: len(x) == 1).shape[0] / len(modcloth_unique_item)
print('modcloth: ' + str(modcloth_one_item))

runway: 192544
modcloth: 82790
users
runway: 105571
modcloth: 47958
items
runway: 30815
modcloth: 5005
fit
runway: 0.7377949975070633
modcloth: 0.6855538108467206
small
runway: 0.13388628053847432
modcloth: 0.15670974755405243
large
runway: 0.12831872195446237
modcloth: 0.15773644159922695
1 user
runway: 0.37302642512880174
modcloth: 0.38494987317308854
1 item
runway: 0.26036021418140515
modcloth: 0.40539460539460537


In [ ]:
#number of unique users
n_users = merged['user_id'].nunique()
n_items = merged['item_id'].nunique()
n_users, n_items

(148475, 7225)

In [ ]:
#missing values
nan_count = merged.isna().sum()
nan_count

item_id         0
size            0
height       1784
fit             0
user_id         0
weight     112772
dtype: int64

In [ ]:
#distribution of fit
merged['fit'].value_counts()

fit      198815
small     38753
large     37766
Name: fit, dtype: int64

In [ ]:
merged_labels = merged.replace({'fit': 0, 'small': -1, 'large': 1})
merged_labels

item_id  size  height  fit user_id weight
0        123373     7      66   -1  991571    NaN
1        123373    13      62   -1  587883    NaN
2        123373     7      67   -1  395665    NaN
3        123373    21    <NA>    0  875643    NaN
4        123373    18      62   -1  944840    NaN
...         ...   ...     ...  ...     ...    ...
275329  2252812     8      69    0   66386    140
275330   682043     4      61    0  118398    100
275331   683251     8      68    0   47002    135
275332   126335    16      66    0  961120    165
275333   127865    16      66    0  123612    155

[275334 rows x 6 columns]

In [ ]:
bpr_data1 = merged.replace({'fit': 1, 'small': 0, 'large': 0})
bpr_data2 = merged[merged['fit'] != 'fit'].replace({'small': 0, 'large': 1})
bpr_data1 = bpr_data1[['user_id', 'item_id', 'fit']]
bpr_data2 = bpr_data2[['user_id', 'item_id', 'fit']]


# Baseline Model

One vs Rest Classifier using svm.SVC

In [ ]:
#imports
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [ ]:
# Drop NaN and split into train, validation, and test
runway_clean = runway.dropna()
X = runway_clean[['weight', 'height']]
y = runway_clean['fit']
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y,
                                            test_size=0.25)

In [ ]:
# Scale the data and fit the model
clf = make_pipeline(StandardScaler(),
                     SGDClassifier(max_iter=1000, tol=1e-3))
clf.fit(X_train, y_train)

In [ ]:
train

array([['149459', '513095', 'fit', 64, '105'],
       ['1463604', '846284', 'small', 68, '127'],
       ['1113191', '769732', 'fit', 63, nan],
       ...,
       ['343137', '372544', 'fit', 64, '145'],
       ['291364', '71161', 'large', 63, '117'],
       ['148089', '636334', 'fit', 67, nan]], dtype=object)

In [ ]:
# Predict
y_pred = clf.predict(X_test)
y_pred

In [ ]:
# Calculate accuracy
correct = sum(y_test == y_pred)
acc = (correct) / len(y_test)
acc

KeyboardInterrupt: ignored

# Baselin v2

In [ ]:
#three tests
data1 = merged.replace({'fit': 1, 'small': 0, 'large': 0})
data2 = merged.replace({'fit': 0, 'small': 1, 'large': 0})
data3 = merged.replace({'fit': 0, 'small': 0, 'large': 1})
data1 = data1[['user_id', 'item_id', 'fit']]
data2 = data2[['user_id', 'item_id', 'fit']]
data3 = data3[['user_id', 'item_id', 'fit']]

In [ ]:
# #split into train, validation, and test
# shuffled_df = merged.sample(frac = 1, random_state=42)

# train, validate = np.split(shuffled_df,
#                        [int(.8*len(shuffled_df))])

In [ ]:
#split into train, validation, and test
import random
random.seed(1)
shuffled_df = data1.sample(frac = 1, random_state=42)

train1, validate1 = np.split(shuffled_df,
                       [int(.8*len(shuffled_df))])
random.seed(1)
shuffled_df2 = data2.sample(frac = 1, random_state=42)

train2, validate2 = np.split(shuffled_df2,
                       [int(.8*len(shuffled_df))])
random.seed(1)
shuffled_df3 = data3.sample(frac = 1, random_state=42)

train3, validate3 = np.split(shuffled_df3,
                       [int(.8*len(shuffled_df))])

In [ ]:
fitTrain = train1[['user_id', 'item_id', 'fit']].to_numpy()
fitValid = validate1[['user_id', 'item_id', 'fit']].to_numpy()
fitTrain2 = train2[['user_id', 'item_id', 'fit']].to_numpy()
fitValid2 = validate2[['user_id', 'item_id', 'fit']].to_numpy()
fitTrain3 = train3[['user_id', 'item_id', 'fit']].to_numpy()
fitValid3 = validate3[['user_id', 'item_id', 'fit']].to_numpy()

In [ ]:
temp = train1.set_index('user_id')[['item_id', 'fit']]
temp['tup'] = temp.apply(lambda row: (row['item_id'],row['fit']),axis=1)
fitPerUser = temp.reset_index().groupby('user_id')['tup'].agg(list).to_dict()

temp2 = train1.set_index('item_id')[['user_id', 'fit']]
temp2['tup'] = temp2.apply(lambda row: (row['user_id'],row['fit']),axis=1)
fitPerItem = temp2.reset_index().groupby('item_id')['tup'].agg(list).to_dict()

In [ ]:
temp = train2.set_index('user_id')[['item_id', 'fit']]
temp['tup'] = temp.apply(lambda row: (row['item_id'],row['fit']),axis=1)
fitPerUser2 = temp.reset_index().groupby('user_id')['tup'].agg(list).to_dict()

temp2 = train2.set_index('item_id')[['user_id', 'fit']]
temp2['tup'] = temp2.apply(lambda row: (row['user_id'],row['fit']),axis=1)
fitPerItem2 = temp2.reset_index().groupby('item_id')['tup'].agg(list).to_dict()

In [ ]:
temp = train3.set_index('user_id')[['item_id', 'fit']]
temp['tup'] = temp.apply(lambda row: (row['item_id'],row['fit']),axis=1)
fitPerUser3 = temp.reset_index().groupby('user_id')['tup'].agg(list).to_dict()

temp2 = train3.set_index('item_id')[['user_id', 'fit']]
temp2['tup'] = temp2.apply(lambda row: (row['user_id'],row['fit']),axis=1)
fitPerItem3 = temp2.reset_index().groupby('item_id')['tup'].agg(list).to_dict()

In [ ]:
betaU = {}
betaI = {}
for u in fitPerUser:
    betaU[u] = 0

for g in fitPerItem:
    betaI[g] = 0

In [ ]:
betaU2 = {}
betaI2 = {}
for u in fitPerUser2:
    betaU2[u] = 0

for g in fitPerItem2:
    betaI2[g] = 0

In [ ]:
betaU3 = {}
betaI3 = {}
for u in fitPerUser3:
    betaU3[u] = 0

for g in fitPerItem3:
    betaI3[g] = 0

In [ ]:
train1['fit'].mean(), train2['fit'].mean(), train3['fit'].mean()

(0.7221417643133107, 0.14084270453585876, 0.1370155311508306)

In [ ]:
alpha1 = 0.75
alpha2 = 0.14
alpha3 = 0.14

In [ ]:
def iterate(lamb):
    newAlpha = 0
    for u,g,r in fitTrain:
        newAlpha += r - (betaU[u] + betaI[g])
    alpha = newAlpha / len(fitTrain)
    for u in fitPerUser:
        newBetaU = 0
        for tup in fitPerUser[u]:
          g = tup[0]
          r = tup[1]
          newBetaU += r - (alpha1 + betaI[g])
        betaU[u] = newBetaU / (lamb + len(fitPerUser[u]))
    for g in fitPerItem:
        newBetaI = 0
        for u,r in fitPerItem[g]:
            newBetaI += r - (alpha1 + betaU[u])
        betaI[g] = newBetaI / (lamb + len(fitPerItem[g]))
    mse = 0
    for u,g,r in fitTrain:
        prediction = alpha1 + betaU[u] + betaI[g]
        mse += (r - prediction)**2
    regularizer = 0
    for u in betaU:
        regularizer += betaU[u]**2
    for g in betaI:
        regularizer += betaI[g]**2
    mse /= len(fitTrain)
    return mse, mse + lamb*regularizer

In [ ]:
def iterate2(lamb):
    newAlpha = 0
    for u,g,r in fitTrain2:
        newAlpha += r - (betaU2[u] + betaI2[g])
    alpha2 = newAlpha / len(fitTrain2)
    for u in fitPerUser2:
        newBetaU = 0
        for tup in fitPerUser2[u]:
          g = tup[0]
          r = tup[1]
          newBetaU += r - (alpha2 + betaI2[g])
        betaU2[u] = newBetaU / (lamb + len(fitPerUser2[u]))
    for g in fitPerItem2:
        newBetaI = 0
        for u,r in fitPerItem2[g]:
            newBetaI += r - (alpha2 + betaU2[u])
        betaI2[g] = newBetaI / (lamb + len(fitPerItem2[g]))
    mse = 0
    for u,g,r in fitTrain2:
        prediction = alpha2 + betaU2[u] + betaI2[g]
        mse += (r - prediction)**2
    regularizer = 0
    for u in betaU2:
        regularizer += betaU2[u]**2
    for g in betaI2:
        regularizer += betaI2[g]**2
    mse /= len(fitTrain2)
    return mse, mse + lamb*regularizer

In [ ]:
def iterate3(lamb):
    newAlpha = 0
    for u,g,r in fitTrain3:
        newAlpha += r - (betaU3[u] + betaI3[g])
    alpha3 = newAlpha / len(fitTrain3)
    for u in fitPerUser3:
        newBetaU = 0
        for tup in fitPerUser2[u]:
          g = tup[0]
          r = tup[1]
          newBetaU += r - (alpha3 + betaI3[g])
        betaU3[u] = newBetaU / (lamb + len(fitPerUser3[u]))
    for g in fitPerItem3:
        newBetaI = 0
        for u,r in fitPerItem3[g]:
            newBetaI += r - (alpha3 + betaU3[u])
        betaI3[g] = newBetaI / (lamb + len(fitPerItem3[g]))
    mse = 0
    for u,g,r in fitTrain3:
        prediction = alpha3 + betaU3[u] + betaI3[g]
        mse += (r - prediction)**2
    regularizer = 0
    for u in betaU3:
        regularizer += betaU3[u]**2
    for g in betaI3:
        regularizer += betaI3[g]**2
    mse /= len(fitTrain3)
    return mse, mse + lamb*regularizer

In [ ]:
mse,objective = iterate(1)
newMSE,newObjective = iterate(1)
iterations = 2

In [ ]:
while iterations < 20 or objective - newObjective > 0.01:
    mse, objective = newMSE, newObjective
    newMSE, newObjective = iterate(1)
    iterations += 1
    print("Objective after "
        + str(iterations) + " iterations = " + str(newObjective))
    print("MSE after "
        + str(iterations) + " iterations = " + str(newMSE))

Objective after 3 iterations = 5724.387639703278
MSE after 3 iterations = 0.08940058247901406
Objective after 4 iterations = 5719.442261243332
MSE after 4 iterations = 0.08934036381994123
Objective after 5 iterations = 5718.843860908689
MSE after 5 iterations = 0.08932475523923374
Objective after 6 iterations = 5718.625994524013
MSE after 6 iterations = 0.08932038830353431
Objective after 7 iterations = 5718.453229526587
MSE after 7 iterations = 0.08931926519579306
Objective after 8 iterations = 5718.321559329606
MSE after 8 iterations = 0.08931910714006087
Objective after 9 iterations = 5718.229805221506
MSE after 9 iterations = 0.08931920879003441
Objective after 10 iterations = 5718.168821391952
MSE after 10 iterations = 0.08931935133897591
Objective after 11 iterations = 5718.129091872914
MSE after 11 iterations = 0.08931947372834736
Objective after 12 iterations = 5718.103364885203
MSE after 12 iterations = 0.08931956531750151
Objective after 13 iterations = 5718.0866975586805
MSE

In [ ]:
mse2,objective2 = iterate2(1)
newMSE2,newObjective2 = iterate2(1)
iterations = 2

In [ ]:
while iterations < 20 or objective - newObjective > 0.01:
    mse2, objective2 = newMSE2, newObjective2
    newMSE2, newObjective2 = iterate2(1)
    iterations += 1
    print("Objective after "
        + str(iterations) + " iterations = " + str(newObjective2))
    print("MSE after "
        + str(iterations) + " iterations = " + str(newMSE2))

Objective after 3 iterations = 3342.9575210760013
MSE after 3 iterations = 0.05094795999856833
Objective after 4 iterations = 3344.821688466511
MSE after 4 iterations = 0.0508736377850449
Objective after 5 iterations = 3347.6272864446046
MSE after 5 iterations = 0.050850061884250564
Objective after 6 iterations = 3349.0949260694438
MSE after 6 iterations = 0.05084140531410033
Objective after 7 iterations = 3349.763899491672
MSE after 7 iterations = 0.050837942917191285
Objective after 8 iterations = 3350.062983127538
MSE after 8 iterations = 0.05083647504173736
Objective after 9 iterations = 3350.1993995424755
MSE after 9 iterations = 0.05083582089627383
Objective after 10 iterations = 3350.264132032186
MSE after 10 iterations = 0.05083551411419752
Objective after 11 iterations = 3350.296480906291
MSE after 11 iterations = 0.05083536195382439
Objective after 12 iterations = 3350.313625487906
MSE after 12 iterations = 0.050835281763757754
Objective after 13 iterations = 3350.32327531796

In [ ]:
mse3,objective3 = iterate3(1)
newMSE3,newObjective3 = iterate3(1)
iterations = 2

In [ ]:
while iterations < 20 or objective - newObjective > 0.01:
    mse3, objective3 = newMSE3, newObjective3
    newMSE3, newObjective3 = iterate3(1)
    iterations += 1
    print("Objective after "
        + str(iterations) + " iterations = " + str(newObjective3))
    print("MSE after "
        + str(iterations) + " iterations = " + str(newMSE3))

Objective after 3 iterations = 6802.480425671823
MSE after 3 iterations = 0.13434860218336364
Objective after 4 iterations = 7255.566875950034
MSE after 4 iterations = 0.13538648128705855
Objective after 5 iterations = 7443.808045665082
MSE after 5 iterations = 0.1358028560080821
Objective after 6 iterations = 7521.52223766216
MSE after 6 iterations = 0.13597207151116356
Objective after 7 iterations = 7553.776965584
MSE after 7 iterations = 0.13604273217740998
Objective after 8 iterations = 7567.24374257534
MSE after 8 iterations = 0.136073316881776
Objective after 9 iterations = 7572.860690209447
MSE after 9 iterations = 0.13608717136646153
Objective after 10 iterations = 7575.157562312988
MSE after 10 iterations = 0.13609382320700103
Objective after 11 iterations = 7576.034532013124
MSE after 11 iterations = 0.1360972619209453
Objective after 12 iterations = 7576.299792630588
MSE after 12 iterations = 0.1360992070148599
Objective after 13 iterations = 7576.301928110234
MSE after 13 i

In [ ]:
validMSE = 0
predictions = []
for u,g,d in fitValid:
    bu = 0
    bi = 0
    if u in betaU:
        bu = betaU[u]
    if g in betaI:
        bi = betaI[g]
    if u in betaU2:
        bu2 = betaU2[u]
    if g in betaI2:
        bi2 = betaI2[g]
    if u in betaU3:
        bu3 = betaU3[u]
    if g in betaI3:
        bi3 = betaI3[g]
    prediction1 = alpha1 + bu + bi
    prediction2 = alpha2 + bu2 + bi2
    prediction3 = alpha3 + bu3 + bi3
    validMSE += (d - prediction1)**2
    predictions.append([prediction1, prediction2, prediction3])
    # predictions = np.append(predictions, round(prediction, 0))

# validMSE /= len(fitValid)
# accuracy = sum(predictions == np.array([d for u, g, d in fitValid]))/len(fitValid)
# print("Validation MSE = " + str(validMSE))
# print("Validation Accuracy = " + str(accuracy))

In [ ]:
d1 = pd.DataFrame(fitValid)
d2 = pd.DataFrame(fitValid2)
d3 = pd.DataFrame(fitValid3)
y = pd.concat([d1, d2, d3], axis=1).loc[:, 2].to_numpy()

In [ ]:
train_y = y[:len(y)//2]
test_y = y[len(y)//2:]
train_x = predictions[:len(y)//2]
test_x = predictions[len(y)//2:]

In [ ]:
y = [list(i).index(1) for i in train_y]
y_test = [list(i).index(1) for i in test_y]

In [ ]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0).fit(train_x, y)
predictions = np.array(clf.predict(test_x))
sum(predictions == np.array(y_test)) / len(y_test)

0.7341468729570713

In [ ]:
from sklearn.metrics import f1_score, confusion_matrix
f1_score(y_test, predictions, average=None)

array([0.84115327, 0.17613386, 0.22203061])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=11)
clf.fit(train_x, y)
predictions = clf.predict(test_x)

In [ ]:
from sklearn.metrics import f1_score, confusion_matrix
f1_score(y_test, predictions, average=None)

array([0.83224092, 0.18809035, 0.2465264 ])

In [ ]:
from sklearn.metrics import f1_score, confusion_matrix
f1_score(y_test, predictions, average=None)

cf_mat = confusion_matrix(y_test, predictions)
print('Confusion matrix')
print(cf_mat)

Confusion matrix
[[18792   517   614]
 [ 3350   458    60]
 [ 3095    27   621]]


In [ ]:
sum(predictions == np.array(y_test)) / len(y_test)

0.7216895474685843

In [ ]:
mse,objective = iterate(1)
newMSE,newObjective = iterate(1)
iterations = 2

In [ ]:
y = np.array([d for u, g, d in fitValid])
X = predictions.reshape(-1, 1)
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X, y)
clf.predict(X)
sum(clf.predict(X) == y) / len(y)

0.7268781665970545

In [ ]:
pd.DataFrame(predictions)[0].value_counts()

1.0    48927
0.0     6140
Name: 0, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve

cf_mat = confusion_matrix(np.array([d for u, g, d in fitValid]), predictions)
print('Confusion matrix')
print(cf_mat)

Confusion matrix
[[ 2994 12322]
 [ 3146 36605]]


In [ ]:
from sklearn.metrics import f1_score
f1_score(np.array([d for u, g, d in fitValid]), predictions, average='micro')

0.7189423792834183

In [ ]:
f1_score(np.array([d for u, g, d in fitValid]), predictions, average=None)

array([0.27990509, 0.82539683])

Beysian Model

In [ ]:
import tensorflow as tf

In [ ]:
interactions = train.to_numpy()
interactionsTest = validate.to_numpy()

In [ ]:
temp = train.set_index('user_id')[['item_id', 'fit']]
temp['tup'] = temp.apply(lambda row: (row['item_id'],row['fit']),axis=1)
fitPerUser = temp.reset_index().groupby('user_id')['tup'].agg(list).to_dict()

temp2 = train.set_index('item_id')[['user_id', 'fit']]
temp2['tup'] = temp2.apply(lambda row: (row['user_id'],row['fit']),axis=1)
fitPerItem = temp2.reset_index().groupby('item_id')['tup'].agg(list).to_dict()

In [ ]:
items = list(fitPerItem.keys())

In [ ]:
userIDs,itemIDs = {},{}

for idx in train.index:
    u = train['user_id'][idx]
    i = train['item_id'][idx]
    if not u in userIDs: userIDs[u] = len(userIDs)
    if not i in itemIDs: itemIDs[i] = len(itemIDs)

nUsers,nItems = len(userIDs),len(itemIDs)

In [ ]:
class BPRbatch(tf.keras.Model):
    def __init__(self, K, lamb):
        super(BPRbatch, self).__init__()
        # Initialize variables
        self.betaI = tf.Variable(tf.random.normal([len(itemIDs)],stddev=0.001))
        self.gammaU = tf.Variable(tf.random.normal([len(userIDs),K],stddev=0.001))
        self.gammaI = tf.Variable(tf.random.normal([len(itemIDs),K],stddev=0.001))
        # Regularization coefficient
        self.lamb = lamb

    # Prediction for a single instance
    def predict(self, u, i):
        p = self.betaI[i] + tf.tensordot(self.gammaU[u], self.gammaI[i], 1)
        return p

    # Regularizer
    def reg(self):
        return self.lamb * (tf.nn.l2_loss(self.betaI) +\
                            tf.nn.l2_loss(self.gammaU) +\
                            tf.nn.l2_loss(self.gammaI))

    def score(self, sampleU, sampleI):
        u = tf.convert_to_tensor(sampleU, dtype=tf.int32)
        i = tf.convert_to_tensor(sampleI, dtype=tf.int32)
        beta_i = tf.nn.embedding_lookup(self.betaI, i)
        gamma_u = tf.nn.embedding_lookup(self.gammaU, u)
        gamma_i = tf.nn.embedding_lookup(self.gammaI, i)
        x_ui = beta_i + tf.reduce_sum(tf.multiply(gamma_u, gamma_i), 1)
        return x_ui

    def call(self, sampleU, sampleI, sampleJ):
        x_ui = self.score(sampleU, sampleI)
        x_uj = self.score(sampleU, sampleJ)
        return -tf.reduce_mean(tf.math.log(tf.math.sigmoid(x_ui - x_uj)))

In [ ]:
optimizer = tf.keras.optimizers.Adam(0.1)

In [ ]:
modelBPR = BPRbatch(5, 0.00001)

In [ ]:
def trainingStepBPR(model, interactions):
    Nsamples = 50000
    with tf.GradientTape() as tape:
        sampleU, sampleI, sampleJ = [], [], []
        for _ in range(Nsamples):
            u,i,_ = random.choice(interactions) # positive sample
            # j = random.choice(items) # negative sample
            for item in fitPerUser[u]:
                if item[1] == 0:
                  j = item[0]
                #just wrong
                else:
                  j = 0
            if j == 0:
              j = random.choice(items)
              while (j, 1) in fitPerUser[u]:
                j = random.choice(items)
            sampleU.append(userIDs[u])
            sampleI.append(itemIDs[i])
            if j != 0:
              sampleJ.append(itemIDs[j])

        loss = model(sampleU,sampleI,sampleJ)
        loss += model.reg()
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients((grad, var) for
                              (grad, var) in zip(gradients, model.trainable_variables)
                              if grad is not None)
    return loss.numpy()

In [ ]:
for i in range(100):
    obj = trainingStepBPR(modelBPR, interactions)
    if (i % 10 == 9): print("iteration " + str(i+1) + ", objective = " + str(obj))

iteration 10, objective = 0.4565918
iteration 20, objective = 0.4536707
iteration 30, objective = 0.45201233
iteration 40, objective = 0.4508512
iteration 50, objective = 0.4503058
iteration 60, objective = 0.4478249
iteration 70, objective = 0.4502264
iteration 80, objective = 0.4531885
iteration 90, objective = 0.45004964
iteration 100, objective = 0.44822332


In [ ]:
u,i,_ = interactionsTest[0]

In [ ]:
predictions = []
y_test = []
for u, i, _ in interactionsTest:
  if u not in userIDs or i not in itemIDs:
    continue
  else:
    predictions.append(modelBPR.predict(userIDs[u], itemIDs[i]).numpy())
    y_test.append(_)

In [ ]:
df = pd.DataFrame({'pred':predictions, 'y':y_test})
true_median = df.groupby('y').median().loc[1, 'pred']
false_median = df.groupby('y').median().loc[0, 'pred']
sum((df['pred'] >= true_median) == df['y'])/len(df['y'])

0.5158626552111478

KeyError: ignored

In [ ]:
modelBPR.predict(userIDs[u], itemIDs[i]).numpy()

1.4011948

In [ ]:
#standardize the height
#statisfaction by size
# predict the fit of the item ... tbd

#features to use height, weight,

#distribution of fit, small, large